// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// WriterFactory is an autogenerated mock type for the WriterFactory type
type WriterFactory struct {
	mock.Mock
}

// CreateWriter provides a mock function with given fields: name
func (_m *WriterFactory) CreateWriter(name string) io.Writer {
	ret := _m.Called(name)

	var r0 io.Writer
	if rf, ok := ret.Get(0).(func(string) io.Writer); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}

	return r0
}
