// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	io "github.com/finderseyes/piper/pipes/io"
	mock "github.com/stretchr/testify/mock"
)

// WriterFactory is an autogenerated mock type for the WriterFactory type
type WriterFactory struct {
	mock.Mock
}

// CreateWriter provides a mock function with given fields: path
func (_m *WriterFactory) CreateWriter(path string) (io.ClosableWriter, error) {
	ret := _m.Called(path)

	var r0 io.ClosableWriter
	if rf, ok := ret.Get(0).(func(string) io.ClosableWriter); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ClosableWriter)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
