name: Pull Request
on:
  pull_request:

jobs:
  lint-n-test:
    name: lint-n-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.0'
      - name: Test
        run: go test -v ./cmd/... ./pipes/...

